title: Ayesa Dream Couture
description: Where Nature Blooms into Fairytale Dreams
url: "https://www.ayesadreamcouture.com"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
